### ISSUE TITLE
Creating scenarios using openmano-giu, i get an error

### ISSUE THREAD

**Issue by Muwatalli** [nfvlabs/openmano#10]
Hi when I try to create a new scenario using GIU, i always get same error:
Result:error
Data:

I tried several browsers.
I am running openmano on RHEL7.1

Thanks in advance.

**Comment by gerardo-garcia** [comment]
Please provide more details about the error.

Regards

De: Muwatalli [mailto:notifications@github.com]
Enviado el: lunes, 20 de abril de 2015 11:46
Para: nfvlabs/openmano
Asunto: [openmano] Creating scenarios using openmano-giu, i get an error (#10)


Hi when I try to create a new scenario using GIU, i always get same error:
Result:error
Data:

I tried several browsers.
I am running openmano on RHEL7.1

Thanks in advance.

—
Reply to this email directly or view it on GitHub<https://github.com/nfvlabs/openmano/issues/10>.

________________________________

Este mensaje y sus adjuntos se dirigen exclusivamente a su destinatario, puede contener información privilegiada o confidencial y es para uso exclusivo de la persona o entidad de destino. Si no es usted. el destinatario indicado, queda notificado de que la lectura, utilización, divulgación y/o copia sin autorización puede estar prohibida en virtud de la legislación vigente. Si ha recibido este mensaje por error, le rogamos que nos lo comunique inmediatamente por esta misma vía y proceda a su destrucción.

The information contained in this transmission is privileged and confidential information intended only for the use of the individual or entity named above. If the reader of this message is not the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this transmission in error, do not read it. Please immediately reply to the sender that you have received this communication in error and then delete it.

Esta mensagem e seus anexos se dirigem exclusivamente ao seu destinatário, pode conter informação privilegiada ou confidencial e é para uso exclusivo da pessoa ou entidade de destino. Se não é vossa senhoria o destinatário indicado, fica notificado de que a leitura, utilização, divulgação e/ou cópia sem autorização pode estar proibida em virtude da legislação vigente. Se recebeu esta mensagem por erro, rogamos-lhe que nos o comunique imediatamente por esta mesma via e proceda a sua destruição

**Comment by alf-tierno** [comment]
For example the exit of
cat ./openmano-gui/config.php
cat ./openmano/openmanod.cfg
openmano tenant-list

Note that you must create a tenant and put this tenant at./openmano-gui/config.php

Regards

De: Gerardo García [mailto:notifications@github.com]
Enviado el: lunes, 20 de abril de 2015 11:51
Para: nfvlabs/openmano
Asunto: Re: [openmano] Creating scenarios using openmano-giu, i get an error (#10)

Please provide more details about the error.

Regards

De: Muwatalli [mailto:notifications@github.com]
Enviado el: lunes, 20 de abril de 2015 11:46
Para: nfvlabs/openmano
Asunto: [openmano] Creating scenarios using openmano-giu, i get an error (#10)


Hi when I try to create a new scenario using GIU, i always get same error:
Result:error
Data:

I tried several browsers.
I am running openmano on RHEL7.1

Thanks in advance.

—
Reply to this email directly or view it on GitHub<https://github.com/nfvlabs/openmano/issues/10>.

________________________________

Este mensaje y sus adjuntos se dirigen exclusivamente a su destinatario, puede contener información privilegiada o confidencial y es para uso exclusivo de la persona o entidad de destino. Si no es usted. el destinatario indicado, queda notificado de que la lectura, utilización, divulgación y/o copia sin autorización puede estar prohibida en virtud de la legislación vigente. Si ha recibido este mensaje por error, le rogamos que nos lo comunique inmediatamente por esta misma vía y proceda a su destrucción.

The information contained in this transmission is privileged and confidential information intended only for the use of the individual or entity named above. If the reader of this message is not the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this transmission in error, do not read it. Please immediately reply to the sender that you have received this communication in error and then delete it.

Esta mensagem e seus anexos se dirigem exclusivamente ao seu destinatário, pode conter informação privilegiada ou confidencial e é para uso exclusivo da pessoa ou entidade de destino. Se não é vossa senhoria o destinatário indicado, fica notificado de que a leitura, utilização, divulgação e/ou cópia sem autorização pode estar proibida em virtude da legislação vigente. Se recebeu esta mensagem por erro, rogamos-lhe que nos o comunique imediatamente por esta mesma via e proceda a sua destruição


—
Reply to this email directly or view it on GitHub<https://github.com/nfvlabs/openmano/issues/10#issuecomment-94410607>.

________________________________

Este mensaje y sus adjuntos se dirigen exclusivamente a su destinatario, puede contener información privilegiada o confidencial y es para uso exclusivo de la persona o entidad de destino. Si no es usted. el destinatario indicado, queda notificado de que la lectura, utilización, divulgación y/o copia sin autorización puede estar prohibida en virtud de la legislación vigente. Si ha recibido este mensaje por error, le rogamos que nos lo comunique inmediatamente por esta misma vía y proceda a su destrucción.

The information contained in this transmission is privileged and confidential information intended only for the use of the individual or entity named above. If the reader of this message is not the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this transmission in error, do not read it. Please immediately reply to the sender that you have received this communication in error and then delete it.

Esta mensagem e seus anexos se dirigem exclusivamente ao seu destinatário, pode conter informação privilegiada ou confidencial e é para uso exclusivo da pessoa ou entidade de destino. Se não é vossa senhoria o destinatário indicado, fica notificado de que a leitura, utilização, divulgação e/ou cópia sem autorização pode estar proibida em virtude da legislação vigente. Se recebeu esta mensagem por erro, rogamos-lhe que nos o comunique imediatamente por esta mesma via e proceda a sua destruição

**Comment by Muwatalli** [comment]
Hi Gerardo.

not too much to add.

using openmano client everithing works, i can create a test enviroment folowwing the guide. 


openmano vnf-list
27f718ee-e743-11e4-b85b-525400dd7445   dataplaneVNF2
9f0bbdf0-e742-11e4-b85b-525400dd7445   dataplaneVNF1
d1e255e6-e73c-11e4-b85b-525400dd7445   linux

openmano scenario-list
cac5892a-e743-11e4-b85b-525400dd7445   simple

openmano instance-scenario-list
d49845d2-e743-11e4-b85b-525400dd7445   simple-mau

**Comment by ozroc** [comment]
Same issue here.
Tenant correctly created and added to openmano-gui/config.php, but when trying to save an error message appears with the useless message:

    Result: error
    Data: 

Where should I look for logs?

**Comment by gerardo-garcia** [comment]
You need to set up in the file config.php the variable **$mano_http** to a value like the one below, using the right IP address where openmano server is running (e.g. 10.10.10.10):

    $mano_http='http://10.10.10.10:9090/openmano'

I have added a comment to the wiki.

**Comment by alf-tierno** [comment]
New version of openmano-gui commited on 21/April/2015 removes the ($mano_http) variable of config.php. This version by default takes the URL automaticaly from the web server. Only in case that openmano and openmano-gui run on different servers, it is needed to edit a new ($mano_domain) variable.
