### ISSUE TITLE
Unknown error when trying to get the host info with host-add.sh

### ISSUE THREAD

**Issue by gerardo-garcia** [nfvlabs/openmano#19]
user@host01 ~$ sudo ./host-add.sh user 10.100.0.1 > host01.yaml
./host-add.sh: line 31: 0000:04:11.7: syntax error in expression (error token is ":04:11.7")
./host-add.sh: line 31: 0000:04:11.7: syntax error in expression (error token is ":04:11.7")
./host-add.sh: line 31: 0000:04:11.7: syntax error in expression (error token is ":04:11.7")
./host-add.sh: line 31: 0000:04:11.7: syntax error in expression (error token is ":04:11.7")
./host-add.sh: line 31: 0000:04:11.7: syntax error in expression (error token is ":04:11.7")
./host-add.sh: line 31: 0000:04:11.7: syntax error in expression (error token is ":04:11.7")
./host-add.sh: line 31: 0000:04:11.7: syntax error in expression (error token is ":04:11.7")
./host-add.sh: line 31: 0000:04:11.7: syntax error in expression (error token is ":04:11.7")
./host-add.sh: line 31: 0000:04:11.7: syntax error in expression (error token is ":04:11.7")
./host-add.sh: line 31: 0000:04:11.7: syntax error in expression (error token is ":04:11.7")
./host-add.sh: line 31: 0000:04:11.7: syntax error in expression (error token is ":04:11.7")
./host-add.sh: line 31: 0000:04:11.7: syntax error in expression (error token is ":04:11.7")
./host-add.sh: line 31: 0000:04:11.7: syntax error in expression (error token is ":04:11.7")
./host-add.sh: line 31: 0000:04:11.7: syntax error in expression (error token is ":04:11.7")
./host-add.sh: line 31: 0000:04:11.7: syntax error in expression (error token is ":04:11.7")
./host-add.sh: line 31: 0000:04:11.7: syntax error in expression (error token is ":04:11.7")
./host-add.sh: line 31: 0000:04:11.7: syntax error in expression (error token is ":04:11.7")

The error seems to be related with the procedure for getting the SR-IOV interfaces.

**Comment by pamonmo** [comment]
The script uses libvirt information about interfaces. In case VF driver is not loaded the SRIOV information is not in libvirt and the scrip generates that error.

The script has been updated to automatically load the VF driver if it is not loaded and remove it prior exiting
