### ISSUE TITLE
host-create

### ISSUE THREAD

**Issue by Hephaistos90** [nfvlabs/openmano#2]
According to the "get started" part of the wiki, one should execute the command './openvim host-create ./test/hosts/host-example0.json'. However openvim returns an error that host-create is an invalid choice. Should this be host-add?

**Comment by alf-tierno** [comment]
Yes, in lastest version we have changed host-create by host-add. And host-delete by host-remove.
Thank you for let us know this mistake

Hephaistos90 <notifications@github.com> wrote:



According to the "get started" part of the wiki, one should execute the command './openvim host-create ./test/hosts/host-example0.json'. However openvim returns an error that host-create is an invalid choice. Should this be host-add?

—
Reply to this email directly or view it on GitHub<https://github.com/nfvlabs/openmano/issues/2>.

________________________________

Este mensaje y sus adjuntos se dirigen exclusivamente a su destinatario, puede contener información privilegiada o confidencial y es para uso exclusivo de la persona o entidad de destino. Si no es usted. el destinatario indicado, queda notificado de que la lectura, utilización, divulgación y/o copia sin autorización puede estar prohibida en virtud de la legislación vigente. Si ha recibido este mensaje por error, le rogamos que nos lo comunique inmediatamente por esta misma vía y proceda a su destrucción.

The information contained in this transmission is privileged and confidential information intended only for the use of the individual or entity named above. If the reader of this message is not the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this transmission in error, do not read it. Please immediately reply to the sender that you have received this communication in error and then delete it.

Esta mensagem e seus anexos se dirigem exclusivamente ao seu destinatário, pode conter informação privilegiada ou confidencial e é para uso exclusivo da pessoa ou entidade de destino. Se não é vossa senhoria o destinatário indicado, fica notificado de que a leitura, utilização, divulgação e/ou cópia sem autorização pode estar proibida em virtude da legislação vigente. Se recebeu esta mensagem por erro, rogamos-lhe que nos o comunique imediatamente por esta mesma via e proceda a sua destruição

**Comment by alf-tierno** [comment]
Yes, in latest version we have changed host-create by host-add; and host-delete by host-remove.

Thank you for let us know this mistake

Sorry if you receive several copies of this email
--
Alfonso Tierno

De: Hephaistos90 [mailto:notifications@github.com]
Enviado el: sábado, 04 de abril de 2015 16:16
Para: nfvlabs/openmano
Asunto: [openmano] host-create (#2)


According to the "get started" part of the wiki, one should execute the command './openvim host-create ./test/hosts/host-example0.json'. However openvim returns an error that host-create is an invalid choice. Should this be host-add?

________________________________

Este mensaje y sus adjuntos se dirigen exclusivamente a su destinatario, puede contener información privilegiada o confidencial y es para uso exclusivo de la persona o entidad de destino. Si no es usted. el destinatario indicado, queda notificado de que la lectura, utilización, divulgación y/o copia sin autorización puede estar prohibida en virtud de la legislación vigente. Si ha recibido este mensaje por error, le rogamos que nos lo comunique inmediatamente por esta misma vía y proceda a su destrucción.

The information contained in this transmission is privileged and confidential information intended only for the use of the individual or entity named above. If the reader of this message is not the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this transmission in error, do not read it. Please immediately reply to the sender that you have received this communication in error and then delete it.

Esta mensagem e seus anexos se dirigem exclusivamente ao seu destinatário, pode conter informação privilegiada ou confidencial e é para uso exclusivo da pessoa ou entidade de destino. Se não é vossa senhoria o destinatário indicado, fica notificado de que a leitura, utilização, divulgação e/ou cópia sem autorização pode estar proibida em virtude da legislação vigente. Se recebeu esta mensagem por erro, rogamos-lhe que nos o comunique imediatamente por esta mesma via e proceda a sua destruição

**Comment by gerardo-garcia** [comment]
Solved in wiki. No action needed in code.
