### ISSUE TITLE
Floodlight has moved to a new site

### ISSUE THREAD

**Issue by jamiephillips0000** [nfvlabs/openmano#20]
Hi
Floodlight has moved. The link to install floodlight 0.90 is timing out
https://github.com/floodlight/floodlight/issues/573#issuecomment-120283169
The install script for openmano should probably reflect this
Kr
Jamie

**Comment by alf-tierno** [comment]
Thank you Jamie for the info. Applying this change to the instalation script.
Kr
Alfonso
