### ISSUE TITLE
Is This Repo Maintained?

### ISSUE THREAD

**Issue by ofekkazes** [nfvlabs/openmano#38]
Hi,

I'm interested in deploying this on a bare-metal box using one of the distros tested. It seems the project was not updated for the past 5 years.

Is this project still maintained? If not, are there alternatives to this one?

Thank you
Ofek

**Comment by fjramons** [comment]
This repository was deprecated five years ago, when OpenMANO was contributed as component to ETSI OSM. The development has continued there since then.

Please refer to <https://osm.etsi.org/> for instructions on how to install OSM.
