### ISSUE TITLE
Error loading file 'vnfs/examples/dataplaneVNF1.yaml' at position: (2:4): content format error: Failed to parse yaml format

### ISSUE THREAD

**Issue by Muwatalli** [nfvlabs/openmano#9]
trying to create some VNFs using the examples of VNF descriptors provided with the code:
linux.yaml works fine but the other two explamples report me errors:

adminuser@ubuntu1410server:~/openmano/openmano$ ./openmano vnf-create vnfs/examples/dataplaneVNF1.yaml
Error loading file 'vnfs/examples/dataplaneVNF1.yaml' at position: (2:4): content format error: Failed to parse yaml format
adminuser@ubuntu1410server:~/openmano/openmano$ ./openmano vnf-create vnfs/examples/dataplaneVNF2.yaml
invalid format 'u'Dataplane VM with high I/O performance requirements: 3 cores (no hyperthreading), 8 GB hugepages, 2 10G interfaces and 1 SR-IOV interface' does not match '^[^,;()\'"]+$'' at vnf:VNFC:0:description
adminuser@ubuntu1410server:~/openmano/openmano$ ls -la vnfs/examples/
total 20
drwxrwxr-x 2 adminuser adminuser 4096 Apr 17 07:31 .
drwxrwxr-x 3 adminuser adminuser 4096 Apr 13 04:17 ..
-rw-rw-r-- 1 adminuser adminuser 2640 Apr 17 06:19 dataplaneVNF1.yaml
-rw-rw-r-- 1 adminuser adminuser 2592 Apr 17 06:19 dataplaneVNF2.yaml
-rw-rw-r-- 1 adminuser adminuser  884 Apr 17 06:38 linux.yaml
adminuser@ubuntu1410server:~/openmano/openmano$

**Comment by gerardo-garcia** [comment]
It was solved on a commit on April 14th.
Just do a 'git pull', stop the servers and start them again, and it should be solved.
